# back to language cpp to try to bypass osx node failure
---
language: node_js
node_js:
  - 7
cache:
  directories:
  - node_modules
before_script:
  - npm install -g gatsby-cli
# script needed to test, because defaults don't work on osx
script:
  - npm run format
  - gatsby build

deploy:
  provider: pages
  local_dir: build
  repo: aravindballa/aravindballa.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  slack: ab--space:clGeU06zSZvLRmHXGzKU4E1u